// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: classroomMessage.proto
// Protobuf Java Version: 4.29.0

package org.example;

public final class ClassroomMessage {
  private ClassroomMessage() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 0,
      /* suffix= */ "",
      ClassroomMessage.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ClassroomProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.example.ClassroomProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>repeated .org.example.PersonProto students = 2;</code>
     */
    java.util.List<org.example.PersonMessage.PersonProto> 
        getStudentsList();
    /**
     * <code>repeated .org.example.PersonProto students = 2;</code>
     */
    org.example.PersonMessage.PersonProto getStudents(int index);
    /**
     * <code>repeated .org.example.PersonProto students = 2;</code>
     */
    int getStudentsCount();
    /**
     * <code>repeated .org.example.PersonProto students = 2;</code>
     */
    java.util.List<? extends org.example.PersonMessage.PersonProtoOrBuilder> 
        getStudentsOrBuilderList();
    /**
     * <code>repeated .org.example.PersonProto students = 2;</code>
     */
    org.example.PersonMessage.PersonProtoOrBuilder getStudentsOrBuilder(
        int index);

    /**
     * <code>uint32 numberStudents = 3;</code>
     * @return The numberStudents.
     */
    int getNumberStudents();
  }
  /**
   * Protobuf type {@code org.example.ClassroomProto}
   */
  public static final class ClassroomProto extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.example.ClassroomProto)
      ClassroomProtoOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 0,
        /* suffix= */ "",
        ClassroomProto.class.getName());
    }
    // Use ClassroomProto.newBuilder() to construct.
    private ClassroomProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ClassroomProto() {
      name_ = "";
      students_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.ClassroomMessage.internal_static_org_example_ClassroomProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.ClassroomMessage.internal_static_org_example_ClassroomProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.ClassroomMessage.ClassroomProto.class, org.example.ClassroomMessage.ClassroomProto.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STUDENTS_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private java.util.List<org.example.PersonMessage.PersonProto> students_;
    /**
     * <code>repeated .org.example.PersonProto students = 2;</code>
     */
    @java.lang.Override
    public java.util.List<org.example.PersonMessage.PersonProto> getStudentsList() {
      return students_;
    }
    /**
     * <code>repeated .org.example.PersonProto students = 2;</code>
     */
    @java.lang.Override
    public java.util.List<? extends org.example.PersonMessage.PersonProtoOrBuilder> 
        getStudentsOrBuilderList() {
      return students_;
    }
    /**
     * <code>repeated .org.example.PersonProto students = 2;</code>
     */
    @java.lang.Override
    public int getStudentsCount() {
      return students_.size();
    }
    /**
     * <code>repeated .org.example.PersonProto students = 2;</code>
     */
    @java.lang.Override
    public org.example.PersonMessage.PersonProto getStudents(int index) {
      return students_.get(index);
    }
    /**
     * <code>repeated .org.example.PersonProto students = 2;</code>
     */
    @java.lang.Override
    public org.example.PersonMessage.PersonProtoOrBuilder getStudentsOrBuilder(
        int index) {
      return students_.get(index);
    }

    public static final int NUMBERSTUDENTS_FIELD_NUMBER = 3;
    private int numberStudents_ = 0;
    /**
     * <code>uint32 numberStudents = 3;</code>
     * @return The numberStudents.
     */
    @java.lang.Override
    public int getNumberStudents() {
      return numberStudents_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, name_);
      }
      for (int i = 0; i < students_.size(); i++) {
        output.writeMessage(2, students_.get(i));
      }
      if (numberStudents_ != 0) {
        output.writeUInt32(3, numberStudents_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, name_);
      }
      for (int i = 0; i < students_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, students_.get(i));
      }
      if (numberStudents_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, numberStudents_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.example.ClassroomMessage.ClassroomProto)) {
        return super.equals(obj);
      }
      org.example.ClassroomMessage.ClassroomProto other = (org.example.ClassroomMessage.ClassroomProto) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (!getStudentsList()
          .equals(other.getStudentsList())) return false;
      if (getNumberStudents()
          != other.getNumberStudents()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      if (getStudentsCount() > 0) {
        hash = (37 * hash) + STUDENTS_FIELD_NUMBER;
        hash = (53 * hash) + getStudentsList().hashCode();
      }
      hash = (37 * hash) + NUMBERSTUDENTS_FIELD_NUMBER;
      hash = (53 * hash) + getNumberStudents();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.example.ClassroomMessage.ClassroomProto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.ClassroomMessage.ClassroomProto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.ClassroomMessage.ClassroomProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.ClassroomMessage.ClassroomProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.ClassroomMessage.ClassroomProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.ClassroomMessage.ClassroomProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.ClassroomMessage.ClassroomProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.example.ClassroomMessage.ClassroomProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.example.ClassroomMessage.ClassroomProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.example.ClassroomMessage.ClassroomProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.ClassroomMessage.ClassroomProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.example.ClassroomMessage.ClassroomProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.example.ClassroomMessage.ClassroomProto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.example.ClassroomProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.example.ClassroomProto)
        org.example.ClassroomMessage.ClassroomProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.example.ClassroomMessage.internal_static_org_example_ClassroomProto_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.example.ClassroomMessage.internal_static_org_example_ClassroomProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.example.ClassroomMessage.ClassroomProto.class, org.example.ClassroomMessage.ClassroomProto.Builder.class);
      }

      // Construct using org.example.ClassroomMessage.ClassroomProto.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        name_ = "";
        if (studentsBuilder_ == null) {
          students_ = java.util.Collections.emptyList();
        } else {
          students_ = null;
          studentsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        numberStudents_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.example.ClassroomMessage.internal_static_org_example_ClassroomProto_descriptor;
      }

      @java.lang.Override
      public org.example.ClassroomMessage.ClassroomProto getDefaultInstanceForType() {
        return org.example.ClassroomMessage.ClassroomProto.getDefaultInstance();
      }

      @java.lang.Override
      public org.example.ClassroomMessage.ClassroomProto build() {
        org.example.ClassroomMessage.ClassroomProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.example.ClassroomMessage.ClassroomProto buildPartial() {
        org.example.ClassroomMessage.ClassroomProto result = new org.example.ClassroomMessage.ClassroomProto(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(org.example.ClassroomMessage.ClassroomProto result) {
        if (studentsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            students_ = java.util.Collections.unmodifiableList(students_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.students_ = students_;
        } else {
          result.students_ = studentsBuilder_.build();
        }
      }

      private void buildPartial0(org.example.ClassroomMessage.ClassroomProto result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.name_ = name_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.numberStudents_ = numberStudents_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.example.ClassroomMessage.ClassroomProto) {
          return mergeFrom((org.example.ClassroomMessage.ClassroomProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.example.ClassroomMessage.ClassroomProto other) {
        if (other == org.example.ClassroomMessage.ClassroomProto.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (studentsBuilder_ == null) {
          if (!other.students_.isEmpty()) {
            if (students_.isEmpty()) {
              students_ = other.students_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureStudentsIsMutable();
              students_.addAll(other.students_);
            }
            onChanged();
          }
        } else {
          if (!other.students_.isEmpty()) {
            if (studentsBuilder_.isEmpty()) {
              studentsBuilder_.dispose();
              studentsBuilder_ = null;
              students_ = other.students_;
              bitField0_ = (bitField0_ & ~0x00000002);
              studentsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getStudentsFieldBuilder() : null;
            } else {
              studentsBuilder_.addAllMessages(other.students_);
            }
          }
        }
        if (other.getNumberStudents() != 0) {
          setNumberStudents(other.getNumberStudents());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                org.example.PersonMessage.PersonProto m =
                    input.readMessage(
                        org.example.PersonMessage.PersonProto.parser(),
                        extensionRegistry);
                if (studentsBuilder_ == null) {
                  ensureStudentsIsMutable();
                  students_.add(m);
                } else {
                  studentsBuilder_.addMessage(m);
                }
                break;
              } // case 18
              case 24: {
                numberStudents_ = input.readUInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.util.List<org.example.PersonMessage.PersonProto> students_ =
        java.util.Collections.emptyList();
      private void ensureStudentsIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          students_ = new java.util.ArrayList<org.example.PersonMessage.PersonProto>(students_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          org.example.PersonMessage.PersonProto, org.example.PersonMessage.PersonProto.Builder, org.example.PersonMessage.PersonProtoOrBuilder> studentsBuilder_;

      /**
       * <code>repeated .org.example.PersonProto students = 2;</code>
       */
      public java.util.List<org.example.PersonMessage.PersonProto> getStudentsList() {
        if (studentsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(students_);
        } else {
          return studentsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .org.example.PersonProto students = 2;</code>
       */
      public int getStudentsCount() {
        if (studentsBuilder_ == null) {
          return students_.size();
        } else {
          return studentsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .org.example.PersonProto students = 2;</code>
       */
      public org.example.PersonMessage.PersonProto getStudents(int index) {
        if (studentsBuilder_ == null) {
          return students_.get(index);
        } else {
          return studentsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .org.example.PersonProto students = 2;</code>
       */
      public Builder setStudents(
          int index, org.example.PersonMessage.PersonProto value) {
        if (studentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStudentsIsMutable();
          students_.set(index, value);
          onChanged();
        } else {
          studentsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.example.PersonProto students = 2;</code>
       */
      public Builder setStudents(
          int index, org.example.PersonMessage.PersonProto.Builder builderForValue) {
        if (studentsBuilder_ == null) {
          ensureStudentsIsMutable();
          students_.set(index, builderForValue.build());
          onChanged();
        } else {
          studentsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.example.PersonProto students = 2;</code>
       */
      public Builder addStudents(org.example.PersonMessage.PersonProto value) {
        if (studentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStudentsIsMutable();
          students_.add(value);
          onChanged();
        } else {
          studentsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .org.example.PersonProto students = 2;</code>
       */
      public Builder addStudents(
          int index, org.example.PersonMessage.PersonProto value) {
        if (studentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStudentsIsMutable();
          students_.add(index, value);
          onChanged();
        } else {
          studentsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.example.PersonProto students = 2;</code>
       */
      public Builder addStudents(
          org.example.PersonMessage.PersonProto.Builder builderForValue) {
        if (studentsBuilder_ == null) {
          ensureStudentsIsMutable();
          students_.add(builderForValue.build());
          onChanged();
        } else {
          studentsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.example.PersonProto students = 2;</code>
       */
      public Builder addStudents(
          int index, org.example.PersonMessage.PersonProto.Builder builderForValue) {
        if (studentsBuilder_ == null) {
          ensureStudentsIsMutable();
          students_.add(index, builderForValue.build());
          onChanged();
        } else {
          studentsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.example.PersonProto students = 2;</code>
       */
      public Builder addAllStudents(
          java.lang.Iterable<? extends org.example.PersonMessage.PersonProto> values) {
        if (studentsBuilder_ == null) {
          ensureStudentsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, students_);
          onChanged();
        } else {
          studentsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .org.example.PersonProto students = 2;</code>
       */
      public Builder clearStudents() {
        if (studentsBuilder_ == null) {
          students_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          studentsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .org.example.PersonProto students = 2;</code>
       */
      public Builder removeStudents(int index) {
        if (studentsBuilder_ == null) {
          ensureStudentsIsMutable();
          students_.remove(index);
          onChanged();
        } else {
          studentsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .org.example.PersonProto students = 2;</code>
       */
      public org.example.PersonMessage.PersonProto.Builder getStudentsBuilder(
          int index) {
        return getStudentsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .org.example.PersonProto students = 2;</code>
       */
      public org.example.PersonMessage.PersonProtoOrBuilder getStudentsOrBuilder(
          int index) {
        if (studentsBuilder_ == null) {
          return students_.get(index);  } else {
          return studentsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .org.example.PersonProto students = 2;</code>
       */
      public java.util.List<? extends org.example.PersonMessage.PersonProtoOrBuilder> 
           getStudentsOrBuilderList() {
        if (studentsBuilder_ != null) {
          return studentsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(students_);
        }
      }
      /**
       * <code>repeated .org.example.PersonProto students = 2;</code>
       */
      public org.example.PersonMessage.PersonProto.Builder addStudentsBuilder() {
        return getStudentsFieldBuilder().addBuilder(
            org.example.PersonMessage.PersonProto.getDefaultInstance());
      }
      /**
       * <code>repeated .org.example.PersonProto students = 2;</code>
       */
      public org.example.PersonMessage.PersonProto.Builder addStudentsBuilder(
          int index) {
        return getStudentsFieldBuilder().addBuilder(
            index, org.example.PersonMessage.PersonProto.getDefaultInstance());
      }
      /**
       * <code>repeated .org.example.PersonProto students = 2;</code>
       */
      public java.util.List<org.example.PersonMessage.PersonProto.Builder> 
           getStudentsBuilderList() {
        return getStudentsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.example.PersonMessage.PersonProto, org.example.PersonMessage.PersonProto.Builder, org.example.PersonMessage.PersonProtoOrBuilder> 
          getStudentsFieldBuilder() {
        if (studentsBuilder_ == null) {
          studentsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.example.PersonMessage.PersonProto, org.example.PersonMessage.PersonProto.Builder, org.example.PersonMessage.PersonProtoOrBuilder>(
                  students_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          students_ = null;
        }
        return studentsBuilder_;
      }

      private int numberStudents_ ;
      /**
       * <code>uint32 numberStudents = 3;</code>
       * @return The numberStudents.
       */
      @java.lang.Override
      public int getNumberStudents() {
        return numberStudents_;
      }
      /**
       * <code>uint32 numberStudents = 3;</code>
       * @param value The numberStudents to set.
       * @return This builder for chaining.
       */
      public Builder setNumberStudents(int value) {

        numberStudents_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 numberStudents = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearNumberStudents() {
        bitField0_ = (bitField0_ & ~0x00000004);
        numberStudents_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.example.ClassroomProto)
    }

    // @@protoc_insertion_point(class_scope:org.example.ClassroomProto)
    private static final org.example.ClassroomMessage.ClassroomProto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.example.ClassroomMessage.ClassroomProto();
    }

    public static org.example.ClassroomMessage.ClassroomProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ClassroomProto>
        PARSER = new com.google.protobuf.AbstractParser<ClassroomProto>() {
      @java.lang.Override
      public ClassroomProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ClassroomProto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ClassroomProto> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.example.ClassroomMessage.ClassroomProto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_ClassroomProto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_example_ClassroomProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026classroomMessage.proto\022\013org.example\032\023p" +
      "ersonMessage.proto\"b\n\016ClassroomProto\022\014\n\004" +
      "name\030\001 \001(\t\022*\n\010students\030\002 \003(\0132\030.org.examp" +
      "le.PersonProto\022\026\n\016numberStudents\030\003 \001(\rb\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.example.PersonMessage.getDescriptor(),
        });
    internal_static_org_example_ClassroomProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_example_ClassroomProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_example_ClassroomProto_descriptor,
        new java.lang.String[] { "Name", "Students", "NumberStudents", });
    descriptor.resolveAllFeaturesImmutable();
    org.example.PersonMessage.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
