// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: personMessage.proto
// Protobuf Java Version: 4.29.0

package org.example;

public final class PersonMessage {
    private PersonMessage() {}
    static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
                /* major= */ 4,
                /* minor= */ 29,
                /* patch= */ 0,
                /* suffix= */ "",
                PersonMessage.class.getName());
    }
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }
    public interface PersonProtoOrBuilder extends
            // @@protoc_insertion_point(interface_extends:org.example.PersonProto)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>string name = 1;</code>
         * @return The name.
         */
        java.lang.String getName();
        /**
         * <code>string name = 1;</code>
         * @return The bytes for name.
         */
        com.google.protobuf.ByteString
        getNameBytes();

        /**
         * <code>int32 age = 2;</code>
         * @return The age.
         */
        int getAge();

        /**
         * <code>string city = 3;</code>
         * @return The city.
         */
        java.lang.String getCity();
        /**
         * <code>string city = 3;</code>
         * @return The bytes for city.
         */
        com.google.protobuf.ByteString
        getCityBytes();
    }
    /**
     * <pre>
     * Define the Person message
     * </pre>
     *
     * Protobuf type {@code org.example.PersonProto}
     */
    public static final class PersonProto extends
            com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:org.example.PersonProto)
            PersonProtoOrBuilder {
        private static final long serialVersionUID = 0L;
        static {
            com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                    com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
                    /* major= */ 4,
                    /* minor= */ 29,
                    /* patch= */ 0,
                    /* suffix= */ "",
                    PersonProto.class.getName());
        }
        // Use PersonProto.newBuilder() to construct.
        private PersonProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
        }
        private PersonProto() {
            name_ = "";
            city_ = "";
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return org.example.PersonMessage.internal_static_org_example_PersonProto_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return org.example.PersonMessage.internal_static_org_example_PersonProto_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            org.example.PersonMessage.PersonProto.class, org.example.PersonMessage.PersonProto.Builder.class);
        }

        public static final int NAME_FIELD_NUMBER = 1;
        @SuppressWarnings("serial")
        private volatile java.lang.Object name_ = "";
        /**
         * <code>string name = 1;</code>
         * @return The name.
         */
        @java.lang.Override
        public java.lang.String getName() {
            java.lang.Object ref = name_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                name_ = s;
                return s;
            }
        }
        /**
         * <code>string name = 1;</code>
         * @return The bytes for name.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getNameBytes() {
            java.lang.Object ref = name_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                name_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int AGE_FIELD_NUMBER = 2;
        private int age_ = 0;
        /**
         * <code>int32 age = 2;</code>
         * @return The age.
         */
        @java.lang.Override
        public int getAge() {
            return age_;
        }

        public static final int CITY_FIELD_NUMBER = 3;
        @SuppressWarnings("serial")
        private volatile java.lang.Object city_ = "";
        /**
         * <code>string city = 3;</code>
         * @return The city.
         */
        @java.lang.Override
        public java.lang.String getCity() {
            java.lang.Object ref = city_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                city_ = s;
                return s;
            }
        }
        /**
         * <code>string city = 3;</code>
         * @return The bytes for city.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getCityBytes() {
            java.lang.Object ref = city_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                city_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private byte memoizedIsInitialized = -1;
        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
                com.google.protobuf.GeneratedMessage.writeString(output, 1, name_);
            }
            if (age_ != 0) {
                output.writeInt32(2, age_);
            }
            if (!com.google.protobuf.GeneratedMessage.isStringEmpty(city_)) {
                com.google.protobuf.GeneratedMessage.writeString(output, 3, city_);
            }
            getUnknownFields().writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
                size += com.google.protobuf.GeneratedMessage.computeStringSize(1, name_);
            }
            if (age_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(2, age_);
            }
            if (!com.google.protobuf.GeneratedMessage.isStringEmpty(city_)) {
                size += com.google.protobuf.GeneratedMessage.computeStringSize(3, city_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof org.example.PersonMessage.PersonProto)) {
                return super.equals(obj);
            }
            org.example.PersonMessage.PersonProto other = (org.example.PersonMessage.PersonProto) obj;

            if (!getName()
                    .equals(other.getName())) return false;
            if (getAge()
                    != other.getAge()) return false;
            if (!getCity()
                    .equals(other.getCity())) return false;
            if (!getUnknownFields().equals(other.getUnknownFields())) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + NAME_FIELD_NUMBER;
            hash = (53 * hash) + getName().hashCode();
            hash = (37 * hash) + AGE_FIELD_NUMBER;
            hash = (53 * hash) + getAge();
            hash = (37 * hash) + CITY_FIELD_NUMBER;
            hash = (53 * hash) + getCity().hashCode();
            hash = (29 * hash) + getUnknownFields().hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static org.example.PersonMessage.PersonProto parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static org.example.PersonMessage.PersonProto parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static org.example.PersonMessage.PersonProto parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static org.example.PersonMessage.PersonProto parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static org.example.PersonMessage.PersonProto parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static org.example.PersonMessage.PersonProto parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static org.example.PersonMessage.PersonProto parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input);
        }
        public static org.example.PersonMessage.PersonProto parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static org.example.PersonMessage.PersonProto parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static org.example.PersonMessage.PersonProto parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static org.example.PersonMessage.PersonProto parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input);
        }
        public static org.example.PersonMessage.PersonProto parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(org.example.PersonMessage.PersonProto prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * <pre>
         * Define the Person message
         * </pre>
         *
         * Protobuf type {@code org.example.PersonProto}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:org.example.PersonProto)
                org.example.PersonMessage.PersonProtoOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return org.example.PersonMessage.internal_static_org_example_PersonProto_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return org.example.PersonMessage.internal_static_org_example_PersonProto_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                org.example.PersonMessage.PersonProto.class, org.example.PersonMessage.PersonProto.Builder.class);
            }

            // Construct using org.example.PersonMessage.PersonProto.newBuilder()
            private Builder() {

            }

            private Builder(
                    com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);

            }
            @java.lang.Override
            public Builder clear() {
                super.clear();
                bitField0_ = 0;
                name_ = "";
                age_ = 0;
                city_ = "";
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return org.example.PersonMessage.internal_static_org_example_PersonProto_descriptor;
            }

            @java.lang.Override
            public org.example.PersonMessage.PersonProto getDefaultInstanceForType() {
                return org.example.PersonMessage.PersonProto.getDefaultInstance();
            }

            @java.lang.Override
            public org.example.PersonMessage.PersonProto build() {
                org.example.PersonMessage.PersonProto result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public org.example.PersonMessage.PersonProto buildPartial() {
                org.example.PersonMessage.PersonProto result = new org.example.PersonMessage.PersonProto(this);
                if (bitField0_ != 0) { buildPartial0(result); }
                onBuilt();
                return result;
            }

            private void buildPartial0(org.example.PersonMessage.PersonProto result) {
                int from_bitField0_ = bitField0_;
                if (((from_bitField0_ & 0x00000001) != 0)) {
                    result.name_ = name_;
                }
                if (((from_bitField0_ & 0x00000002) != 0)) {
                    result.age_ = age_;
                }
                if (((from_bitField0_ & 0x00000004) != 0)) {
                    result.city_ = city_;
                }
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof org.example.PersonMessage.PersonProto) {
                    return mergeFrom((org.example.PersonMessage.PersonProto)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(org.example.PersonMessage.PersonProto other) {
                if (other == org.example.PersonMessage.PersonProto.getDefaultInstance()) return this;
                if (!other.getName().isEmpty()) {
                    name_ = other.name_;
                    bitField0_ |= 0x00000001;
                    onChanged();
                }
                if (other.getAge() != 0) {
                    setAge(other.getAge());
                }
                if (!other.getCity().isEmpty()) {
                    city_ = other.city_;
                    bitField0_ |= 0x00000004;
                    onChanged();
                }
                this.mergeUnknownFields(other.getUnknownFields());
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                if (extensionRegistry == null) {
                    throw new java.lang.NullPointerException();
                }
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0:
                                done = true;
                                break;
                            case 10: {
                                name_ = input.readStringRequireUtf8();
                                bitField0_ |= 0x00000001;
                                break;
                            } // case 10
                            case 16: {
                                age_ = input.readInt32();
                                bitField0_ |= 0x00000002;
                                break;
                            } // case 16
                            case 26: {
                                city_ = input.readStringRequireUtf8();
                                bitField0_ |= 0x00000004;
                                break;
                            } // case 26
                            default: {
                                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                    done = true; // was an endgroup tag
                                }
                                break;
                            } // default:
                        } // switch (tag)
                    } // while (!done)
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.unwrapIOException();
                } finally {
                    onChanged();
                } // finally
                return this;
            }
            private int bitField0_;

            private java.lang.Object name_ = "";
            /**
             * <code>string name = 1;</code>
             * @return The name.
             */
            public java.lang.String getName() {
                java.lang.Object ref = name_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    name_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>string name = 1;</code>
             * @return The bytes for name.
             */
            public com.google.protobuf.ByteString
            getNameBytes() {
                java.lang.Object ref = name_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    name_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>string name = 1;</code>
             * @param value The name to set.
             * @return This builder for chaining.
             */
            public Builder setName(
                    java.lang.String value) {
                if (value == null) { throw new NullPointerException(); }
                name_ = value;
                bitField0_ |= 0x00000001;
                onChanged();
                return this;
            }
            /**
             * <code>string name = 1;</code>
             * @return This builder for chaining.
             */
            public Builder clearName() {
                name_ = getDefaultInstance().getName();
                bitField0_ = (bitField0_ & ~0x00000001);
                onChanged();
                return this;
            }
            /**
             * <code>string name = 1;</code>
             * @param value The bytes for name to set.
             * @return This builder for chaining.
             */
            public Builder setNameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) { throw new NullPointerException(); }
                checkByteStringIsUtf8(value);
                name_ = value;
                bitField0_ |= 0x00000001;
                onChanged();
                return this;
            }

            private int age_ ;
            /**
             * <code>int32 age = 2;</code>
             * @return The age.
             */
            @java.lang.Override
            public int getAge() {
                return age_;
            }
            /**
             * <code>int32 age = 2;</code>
             * @param value The age to set.
             * @return This builder for chaining.
             */
            public Builder setAge(int value) {

                age_ = value;
                bitField0_ |= 0x00000002;
                onChanged();
                return this;
            }
            /**
             * <code>int32 age = 2;</code>
             * @return This builder for chaining.
             */
            public Builder clearAge() {
                bitField0_ = (bitField0_ & ~0x00000002);
                age_ = 0;
                onChanged();
                return this;
            }

            private java.lang.Object city_ = "";
            /**
             * <code>string city = 3;</code>
             * @return The city.
             */
            public java.lang.String getCity() {
                java.lang.Object ref = city_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    city_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>string city = 3;</code>
             * @return The bytes for city.
             */
            public com.google.protobuf.ByteString
            getCityBytes() {
                java.lang.Object ref = city_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    city_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>string city = 3;</code>
             * @param value The city to set.
             * @return This builder for chaining.
             */
            public Builder setCity(
                    java.lang.String value) {
                if (value == null) { throw new NullPointerException(); }
                city_ = value;
                bitField0_ |= 0x00000004;
                onChanged();
                return this;
            }
            /**
             * <code>string city = 3;</code>
             * @return This builder for chaining.
             */
            public Builder clearCity() {
                city_ = getDefaultInstance().getCity();
                bitField0_ = (bitField0_ & ~0x00000004);
                onChanged();
                return this;
            }
            /**
             * <code>string city = 3;</code>
             * @param value The bytes for city to set.
             * @return This builder for chaining.
             */
            public Builder setCityBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) { throw new NullPointerException(); }
                checkByteStringIsUtf8(value);
                city_ = value;
                bitField0_ |= 0x00000004;
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:org.example.PersonProto)
        }

        // @@protoc_insertion_point(class_scope:org.example.PersonProto)
        private static final org.example.PersonMessage.PersonProto DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new org.example.PersonMessage.PersonProto();
        }

        public static org.example.PersonMessage.PersonProto getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<PersonProto>
                PARSER = new com.google.protobuf.AbstractParser<PersonProto>() {
            @java.lang.Override
            public PersonProto parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                Builder builder = newBuilder();
                try {
                    builder.mergeFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.setUnfinishedMessage(builder.buildPartial());
                } catch (com.google.protobuf.UninitializedMessageException e) {
                    throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
                } catch (java.io.IOException e) {
                    throw new com.google.protobuf.InvalidProtocolBufferException(e)
                            .setUnfinishedMessage(builder.buildPartial());
                }
                return builder.buildPartial();
            }
        };

        public static com.google.protobuf.Parser<PersonProto> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<PersonProto> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public org.example.PersonMessage.PersonProto getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_org_example_PersonProto_descriptor;
    private static final
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_org_example_PersonProto_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    private static  com.google.protobuf.Descriptors.FileDescriptor
            descriptor;
    static {
        java.lang.String[] descriptorData = {
                "\n\023personMessage.proto\022\013org.example\"6\n\013Pe" +
                        "rsonProto\022\014\n\004name\030\001 \001(\t\022\013\n\003age\030\002 \001(\005\022\014\n\004" +
                        "city\030\003 \001(\tb\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[] {
                        });
        internal_static_org_example_PersonProto_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_org_example_PersonProto_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_org_example_PersonProto_descriptor,
                new java.lang.String[] { "Name", "Age", "City", });
        descriptor.resolveAllFeaturesImmutable();
    }

    // @@protoc_insertion_point(outer_class_scope)
}
